from tkinter import *

def add():
    sum=int(e1.get())+int(e2.get())
    e3.delete(0,END)
    e3.insert(0,sum)
def sub():
    sub=int(e1.get())-int(e2.get())
    e3.delete(0,END)
    e3.insert(0,sub)
def mult():
    mult=int(e1.get())*int(e2.get())
    e3.delete(0,END)
    e3.insert(0,mult)
def clear():
    e1.delete(0,END)
    e2.delete(0,END)
window=Tk()
window.title("Welcome to Apps")
window.geometry("400x200")
window.resizable(True,True)
window.configure(background="#14A3C7")
window.iconbitmap("favicon.ico")
#window.attributes("-alpha",0.9)
window.attributes("-topmost",True)

lbl1=Label(text="Enter 1st Number :",bg="#14A3C7", fg="white")
lbl1.place(x=40,y=20)
lbl2=Label(text="Enter 2nd Number :",bg="#14A3C7", fg="white")
lbl2.place(x=40,y=50)
e1=Entry()
e1.place(x=180,y=20)
e2=Entry()
e2.place(x=180,y=50)
btn=Button(text="SUM", background="#14A3C7",fg="white", command=add)
btn.place(x=180,y=90)
btn1=Button(text="SUB", background="#14A3C7",fg="white", command=sub)
btn1.place(x=220,y=90)
btn2=Button(text="MULT", background="#14A3C7",fg="white", command=mult)
btn2.place(x=255,y=90)
btn3=Button(text="Clear", background="#14A3C7",fg="white", command=clear)
btn3.place(x=300,y=90)
e3=Entry()
e3.place(x=180,y=140)
window.mainloop()
